<?php
require_once(__DIR__.'/../../DBC.php');
require_once(__DIR__.'/../../helpers/credentials.php');
require_once(__DIR__.'/../../helpers/validator.php');
require_once(__DIR__.'/../admin_helpers/auth.php');
require_once(__DIR__.'/../admin_helpers/redirect.php');
require_once(__DIR__.'/../admin_helpers/error.php');
require_once(__DIR__.'/../admin_helpers/filesystem.php');
require_once(__DIR__.'/../admin_helpers/output.php');