START TRANSACTION;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS MATERIALS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS PRODUCT_MATERIAL;
DROP TABLE IF EXISTS USER_PRODUCT;
DROP TABLE IF EXISTS QUOTES;
DROP TABLE IF EXISTS QUOTE_PRODUCT;

CREATE TABLE USERS(
    _ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(50) NOT NULL,
    _SURNAME VARCHAR(100) NOT NULL,
    _CITY VARCHAR(100) NOT NULL,
    _ADDRESS VARCHAR(100) NOT NULL,
    _CAP CHAR(5) NOT NULL,
    _ADMIN BIT DEFAULT 0,
    _EMAIL VARCHAR(100) NOT NULL UNIQUE,
    _PASSWORD VARCHAR(1024)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE CATEGORIES(
    _ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(100) NOT NULL,
    _DESCRIPTION TEXT NOT NULL,
    _METADESCRIPTION VARCHAR(500) NOT NULL,
    _MENU BIT DEFAULT 0
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE MATERIALS(
    _ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(50) NOT NULL,
    _DESCRIPTION VARCHAR(200) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE PRODUCTS(
    _ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(30) NOT NULL,
    _DESCRIPTION TEXT NOT NULL,
    _METADESCRIPTION VARCHAR(500) NOT NULL,
    _DIMENSIONS VARCHAR(300),
    _AGE VARCHAR(50),
    _MAIN_IMAGE VARCHAR(500) NOT NULL,
    _CATEGORY INT NOT NULL,
    FOREIGN KEY (_CATEGORY) REFERENCES CATEGORIES(_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE PRODUCT_MATERIAL(
    _MATERIAL_ID INT NOT NULL,
    _PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (_MATERIAL_ID, _PRODUCT_ID),
    FOREIGN KEY (_MATERIAL_ID) REFERENCES MATERIALS(_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (_PRODUCT_ID) REFERENCES PRODUCTS(_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE USER_PRODUCT( /* PRODOTTI VISUALIZZATI E QUANTE VOLTE SON STATI VISUALIZZATI*/
    _QUANTITY INT DEFAULT 1,

    _USER_ID INT NOT NULL,
    _PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (_USER_ID, _PRODUCT_ID),
    FOREIGN KEY(_USER_ID) REFERENCES USERS(_ID)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(_PRODUCT_ID) REFERENCES PRODUCTS(_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE QUOTES(
    _ID INT AUTO_INCREMENT PRIMARY KEY,
    _CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    _TELEPHONE VARCHAR(20),
    _REASON TEXT,
    _COMPANY VARCHAR(100),
    
    _USER INT NOT NULL,
    FOREIGN KEY(_USER) REFERENCES USERS(_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE QUOTE_PRODUCT(
    _QUANTITY INT DEFAULT 1,

    _QUOTE_ID INT NOT NULL,
    _PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (_QUOTE_ID, _PRODUCT_ID),
    FOREIGN KEY(_QUOTE_ID) REFERENCES QUOTES(_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(_PRODUCT_ID) REFERENCES PRODUCTS(_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

INSERT INTO `USERS` (`_ID`, `_NAME`, `_SURNAME`, `_CITY`, `_ADDRESS`, `_CAP`, `_ADMIN`, `_EMAIL`, `_PASSWORD`) VALUES
(1, 'admin name', 'admin surname', 'admin city', 'admin address', '10010', b'1', 'admin@admin.admin', 'admin')

COMMIT;